### ISSUE TITLE
Update from 0.2.0 to 0.2.3 failed

### ISSUE THREAD

**Issue by ssnake** [discourse/mini_racer#113]
Hey guys,
Recently I've upgraded my bundle and things started to fail.
Unable to compile mini_race's dependence `libv8`. It was updated from 6.3.292.48.1 to 6.7.288.46.1

```
current directory: /home/snake/projects/taxibus2/shared/bundle/ruby/2.5.0/gems/libv8-6.7.288.46.1/ext/libv8
/home/snake/.rbenv/versions/2.5.1/bin/ruby -r ./siteconf20181029-22526-3zkn7d.rb extconf.rb
creating Makefile

________ running 'git -c core.deltaBaseCacheLimit=512m clone --no-checkout --progress https://chromium.googlesource.com/v8/v8.git /home/snake/projects/taxibus2/shared/bundle/ruby/2.5.0/gems/libv8-6.7.288.46.1/vendor/_gclient_v8_QhkTpK' in '/home/snake/projects/taxibus2/shared/bundle/ruby/2.5.0/gems/libv8-6.7.288.46.1/vendor'
Cloning into '/home/snake/projects/taxibus2/shared/bundle/ruby/2.5.0/gems/libv8-6.7.288.46.1/vendor/_gclient_v8_QhkTpK'...
remote: Sending approximately 406.83 MiB ...[K
remote: Counting objects: 1   [K
remote: Counting objects: 6583   [K
remote: Counting objects: 7660, done[K
Receiving objects:   0% (1/607285)   
Receiving objects:   1% (6073/607285)   
Receiving objects:   2% (12146/607285)   
Receiving objects:   3% (18219/607285)   
Receiving objects:   4% (24292/607285), 7.68 MiB | 15.33 MiB/s   
Receiving objects:   5% (30365/607285), 7.68 MiB | 15.33 MiB/s   
Receiving objects:   6% (36438/607285), 7.68 MiB | 15.33 MiB/s   
Receiving objects:   6% (38757/607285), 7.68 MiB | 15.33 MiB/s   
Receiving objects:   7% (42510/607285), 15.84 MiB | 15.81 MiB/s   
Receiving objects:   8% (48583/607285), 15.84 MiB | 15.81 MiB/s   
Receiving objects:   9% (54656/607285), 15.84 MiB | 15.81 MiB/s   
Receiving objects:  10% (60729/607285), 15.84 MiB | 15.81 MiB/s   
Receiving objects:  11% (66802/607285), 23.61 MiB | 15.71 MiB/s   
Receiving objects:  12% (72875/607285), 23.61 MiB | 15.71 MiB/s   
Receiving objects:  13% (78948/607285), 23.61 MiB | 15.71 MiB/s   
Receiving objects:  13% (81125/607285), 23.61 MiB | 15.71 MiB/s   
Receiving objects:  14% (85020/607285), 35.64 MiB | 17.78 MiB/s   
Receiving objects:  15% (91093/607285), 35.64 MiB | 17.78 MiB/s   
Receiving objects:  16% (97166/607285), 35.64 MiB | 17.78 MiB/s   
Receiving objects:  17% (103239/607285), 35.64 MiB | 17.78 MiB/s   
Receiving objects:  18% (109312/607285), 50.42 MiB | 20.13 MiB/s   
Receiving objects:  19% (115385/607285), 50.42 MiB | 20.13 MiB/s   
Receiving objects:  20% (121457/607285), 50.42 MiB | 20.13 MiB/s   
Receiving objects:  21% (127530/607285), 50.42 MiB | 20.13 MiB/s   
Receiving objects:  22% (133603/607285), 50.42 MiB | 20.13 MiB/s   
Receiving objects:  22% (138665/607285), 50.42 MiB | 20.13 MiB/s   
Receiving objects:  23% (139676/607285), 50.42 MiB | 20.13 MiB/s   
Receiving objects:  24% (145749/607285), 65.22 MiB | 21.70 MiB/s   
Receiving objects:  25% (151822/607285), 65.22 MiB | 21.70 MiB/s   
Receiving objects:  26% (157895/607285), 65.22 MiB | 21.70 MiB/s   
Receiving objects:  27% (163967/607285), 65.22 MiB | 21.70 MiB/s   
Receiving objects:  28% (170040/607285), 65.22 MiB | 21.70 MiB/s   
Receiving objects:  29% (176113/607285), 65.22 MiB | 21.70 MiB/s   
Receiving objects:  30% (182186/607285), 65.22 MiB | 21.70 MiB/s   
Receiving objects:  31% (188259/607285), 65.22 MiB | 21.70 MiB/s   
Receiving objects:  32% (194332/607285), 65.22 MiB | 21.70 MiB/s   
Receiving objects:  33% (200405/607285), 65.22 MiB | 21.70 MiB/s   
Receiving objects:  34% (206477/607285), 65.22 MiB | 21.70 MiB/s   
Receiving objects:  35% (212550/607285), 65.22 MiB | 21.70 MiB/s   
Receiving objects:  36% (218623/607285), 65.22 MiB | 21.70 MiB/s   
Receiving objects:  37% (224696/607285), 65.22 MiB | 21.70 MiB/s   
Receiving objects:  38% (230769/607285), 65.22 MiB | 21.70 MiB/s   
Receiving objects:  39% (236842/607285), 65.22 MiB | 21.70 MiB/s   
Receiving objects:  40% (242914/607285), 65.22 MiB | 21.70 MiB/s   
Receiving objects:  41% (248987/607285), 65.22 MiB | 21.70 MiB/s   
Receiving objects:  42% (255060/607285), 65.22 MiB | 21.70 MiB/s   
Receiving objects:  43% (261133/607285), 65.22 MiB | 21.70 MiB/s   
Receiving objects:  44% (267206/607285), 65.22 MiB | 21.70 MiB/s   
Receiving objects:  45% (273279/607285), 65.22 MiB | 21.70 MiB/s   
Receiving objects:  46% (279352/607285), 65.22 MiB | 21.70 MiB/s   
Receiving objects:  47% (285424/607285), 65.22 MiB | 21.70 MiB/s   
Receiving objects:  48% (291497/607285), 65.22 MiB | 21.70 MiB/s   
Receiving objects:  49% (297570/607285), 65.22 MiB | 21.70 MiB/s   
Receiving objects:  50% (303643/607285), 65.22 MiB | 21.70 MiB/s   
Receiving objects:  51% (309716/607285), 65.22 MiB | 21.70 MiB/s   
Receiving objects:  52% (315789/607285), 65.22 MiB | 21.70 MiB/s   
Receiving objects:  53% (321862/607285), 65.22 MiB | 21.70 MiB/s   
Receiving objects:  54% (327934/607285), 81.10 MiB | 23.13 MiB/s   
Receiving objects:  54% (329595/607285), 81.10 MiB | 23.13 MiB/s   
Receiving objects:  55% (334007/607285), 102.34 MiB | 22.70 MiB/s   
Receiving objects:  55% (339239/607285), 102.34 MiB | 22.70 MiB/s   
Receiving objects:  56% (340080/607285), 107.04 MiB | 22.03 MiB/s   
Receiving objects:  57% (346153/607285), 118.57 MiB | 22.78 MiB/s   
Receiving objects:  57% (347006/607285), 118.57 MiB | 22.78 MiB/s   
Receiving objects:  58% (352226/607285), 142.99 MiB | 23.81 MiB/s   
Receiving objects:  58% (353462/607285), 142.99 MiB | 23.81 MiB/s   
Receiving objects:  59% (358299/607285), 167.14 MiB | 22.60 MiB/s   
Receiving objects:  59% (358974/607285), 167.14 MiB | 22.60 MiB/s   
Receiving objects:  59% (361432/607285), 191.32 MiB | 18.69 MiB/s   
Receiving objects:  60% (364371/607285), 191.32 MiB | 18.69 MiB/s   
Receiving objects:  60% (366015/607285), 205.27 MiB | 20.64 MiB/s   
Receiving objects:  61% (370444/607285), 225.99 MiB | 20.20 MiB/s   
Receiving objects:  61% (371115/607285), 225.99 MiB | 20.20 MiB/s   
Receiving objects:  62% (376517/607285), 238.11 MiB | 19.98 MiB/s   
Receiving objects:  62% (376530/607285), 250.42 MiB | 18.66 MiB/s   
Receiving objects:  62% (378490/607285), 255.36 MiB | 16.14 MiB/s   
Receiving objects:  63% (382590/607285), 255.36 MiB | 16.14 MiB/s   
Receiving objects:  63% (384833/607285), 280.94 MiB | 17.74 MiB/s   
Receiving objects:  64% (388663/607285), 291.70 MiB | 19.25 MiB/s   
Receiving objects:  64% (389584/607285), 302.35 MiB | 18.62 MiB/s   
Receiving objects:  64% (392293/607285), 322.93 MiB | 18.59 MiB/s   
Receiving objects:  65% (394736/607285), 322.93 MiB | 18.59 MiB/s   
Receiving objects:  65% (399301/607285), 345.42 MiB | 19.66 MiB/s   
Receiving objects:  66% (400809/607285), 345.42 MiB | 19.66 MiB/s   
Receiving objects:  67% (406881/607285), 356.40 MiB | 22.41 MiB/s   
Receiving objects:  68% (412954/607285), 356.40 MiB | 22.41 MiB/s   
Receiving objects:  68% (418053/607285), 367.80 MiB | 21.93 MiB/s   
Receiving objects:  69% (419027/607285), 367.80 MiB | 21.93 MiB/s   
Receiving objects:  70% (425100/607285), 367.80 MiB | 21.93 MiB/s   
Receiving objects:  71% (431173/607285), 367.80 MiB | 21.93 MiB/s   
Receiving objects:  72% (437246/607285), 367.80 MiB | 21.93 MiB/s   
Receiving objects:  73% (443319/607285), 367.80 MiB | 21.93 MiB/s   
Receiving objects:  74% (449391/607285), 367.80 MiB | 21.93 MiB/s   
Receiving objects:  75% (455464/607285), 367.80 MiB | 21.93 MiB/s   
Receiving objects:  76% (461537/607285), 367.80 MiB | 21.93 MiB/s   
Receiving objects:  77% (467610/607285), 367.80 MiB | 21.93 MiB/s   
Receiving objects:  78% (473683/607285), 367.80 MiB | 21.93 MiB/s   
Receiving objects:  79% (479756/607285), 367.80 MiB | 21.93 MiB/s   
Receiving objects:  80% (485828/607285), 367.80 MiB | 21.93 MiB/s   
Receiving objects:  81% (491901/607285), 367.80 MiB | 21.93 MiB/s   
Receiving objects:  82% (497974/607285), 367.80 MiB | 21.93 MiB/s   
Receiving objects:  83% (504047/607285), 367.80 MiB | 21.93 MiB/s   
Receiving objects:  84% (510120/607285), 382.33 MiB | 22.49 MiB/s   
Receiving objects:  85% (516193/607285), 382.33 MiB | 22.49 MiB/s   
Receiving objects:  86% (522266/607285), 382.33 MiB | 22.49 MiB/s   
Receiving objects:  87% (528338/607285), 382.33 MiB | 22.49 MiB/s   
Receiving objects:  88% (534411/607285), 382.33 MiB | 22.49 MiB/s   
Receiving objects:  89% (540484/607285), 382.33 MiB | 22.49 MiB/s   
Receiving objects:  90% (546557/607285), 382.33 MiB | 22.49 MiB/s   
Receiving objects:  91% (552630/607285), 382.33 MiB | 22.49 MiB/s   
Receiving objects:  92% (558703/607285), 382.33 MiB | 22.49 MiB/s   
Receiving objects:  92% (559805/607285), 396.00 MiB | 23.13 MiB/s   
Receiving objects:  93% (564776/607285), 396.00 MiB | 23.13 MiB/s   
Receiving objects:  94% (570848/607285), 396.00 MiB | 23.13 MiB/s   
Receiving objects:  95% (576921/607285), 396.00 MiB | 23.13 MiB/s   
Receiving objects:  96% (582994/607285), 396.00 MiB | 23.13 MiB/s   
Receiving objects:  97% (589067/607285), 396.00 MiB | 23.13 MiB/s   
Receiving objects:  98% (595140/607285), 396.00 MiB | 23.13 MiB/s   
Receiving objects:  99% (601213/607285), 396.00 MiB | 23.13 MiB/s   
remote: Total 607285 (delta 509791), reused 607285 (delta 509791)[K
Receiving objects: 100% (607285/607285), 396.00 MiB | 23.13 MiB/s   
Receiving objects: 100% (607285/607285), 406.64 MiB | 23.37 MiB/s, done.
Resolving deltas:   0% (0/509791)   
Resolving deltas:   1% (6289/509791)   
Resolving deltas:   2% (10199/509791)   
Resolving deltas:   2% (15262/509791)   
Resolving deltas:   3% (15295/509791)   
Resolving deltas:   4% (22911/509791)   
Resolving deltas:   5% (25502/509791)   
Resolving deltas:   6% (30590/509791)   
Resolving deltas:   7% (35686/509791)   
Resolving deltas:   8% (41256/509791)   
Resolving deltas:   8% (44649/509791)   
Resolving deltas:   9% (47026/509791)   
Resolving deltas:  10% (51351/509791)   
Resolving deltas:  11% (56082/509791)   
Resolving deltas:  12% (61422/509791)   
Resolving deltas:  13% (66469/509791)   
Resolving deltas:  13% (69649/509791)   
Resolving deltas:  14% (72686/509791)   
Resolving deltas:  15% (76640/509791)   
Resolving deltas:  16% (81575/509791)   
Resolving deltas:  17% (89596/509791)   
Resolving deltas:  18% (91802/509791)   
Resolving deltas:  19% (99882/509791)   
Resolving deltas:  20% (102929/509791)   
Resolving deltas:  20% (106704/509791)   
Resolving deltas:  21% (107729/509791)   
Resolving deltas:  22% (112985/509791)   
Resolving deltas:  23% (117347/509791)   
Resolving deltas:  24% (122361/509791)   
Resolving deltas:  25% (128049/509791)   
Resolving deltas:  26% (133690/509791)   
Resolving deltas:  27% (137950/509791)   
Resolving deltas:  28% (142758/509791)   
Resolving deltas:  28% (145564/509791)   
Resolving deltas:  29% (150272/509791)   
Resolving deltas:  30% (153197/509791)   
Resolving deltas:  31% (159195/509791)   
Resolving deltas:  32% (164667/509791)   
Resolving deltas:  33% (168476/509791)   
Resolving deltas:  34% (173431/509791)   
Resolving deltas:  35% (178537/509791)   
Resolving deltas:  35% (182878/509791)   
Resolving deltas:  36% (183580/509791)   
Resolving deltas:  37% (188635/509791)   
Resolving deltas:  38% (193786/509791)   
Resolving deltas:  39% (198927/509791)   
Resolving deltas:  40% (204365/509791)   
Resolving deltas:  41% (209243/509791)   
Resolving deltas:  42% (214358/509791)   
Resolving deltas:  42% (215741/509791)   
Resolving deltas:  43% (219378/509791)   
Resolving deltas:  44% (224368/509791)   
Resolving deltas:  45% (229567/509791)   
Resolving deltas:  46% (234533/509791)   
Resolving deltas:  47% (239630/509791)   
Resolving deltas:  48% (244723/509791)   
Resolving deltas:  48% (248830/509791)   
Resolving deltas:  50% (259797/509791)   
Resolving deltas:  51% (260229/509791)   
Resolving deltas:  51% (265061/509791)   
Resolving deltas:  52% (266043/509791)   
Resolving deltas:  53% (270210/509791)   
Resolving deltas:  53% (272129/509791)   
Resolving deltas:  54% (275295/509791)   
Resolving deltas:  54% (278481/509791)   
Resolving deltas:  55% (280426/509791)   
Resolving deltas:  55% (284781/509791)   
Resolving deltas:  56% (285529/509791)   
Resolving deltas:  57% (290584/509791)   
Resolving deltas:  57% (292672/509791)   
Resolving deltas:  57% (294354/509791)   
Resolving deltas:  58% (297302/509791)   
Resolving deltas:  58% (298923/509791)   
Resolving deltas:  59% (300787/509791)   
Resolving deltas:  59% (302672/509791)   
Resolving deltas:  60% (306372/509791)   
Resolving deltas:  60% (309851/509791)   
Resolving deltas:  61% (311680/509791)   
Resolving deltas:  62% (316266/509791)   
Resolving deltas:  62% (317211/509791)   
Resolving deltas:  63% (321185/509791)   
Resolving deltas:  63% (324658/509791)   
Resolving deltas:  64% (326291/509791)   
Resolving deltas:  65% (332151/509791)   
Resolving deltas:  66% (336464/509791)   
[0:01:00] Still working on:
[0:01:00]   v8
Resolving deltas:  66% (341484/509791)   
Resolving deltas:  67% (341578/509791)   
Resolving deltas:  67% (346200/509791)   
Resolving deltas:  68% (346895/509791)   
Resolving deltas:  69% (351894/509791)   
Resolving deltas:  69% (352254/509791)   
Resolving deltas:  69% (356440/509791)   
Resolving deltas:  70% (356898/509791)   
Resolving deltas:  70% (361664/509791)   
Resolving deltas:  71% (362112/509791)   
Resolving deltas:  71% (365639/509791)   
Resolving deltas:  72% (367198/509791)   
Resolving deltas:  72% (369543/509791)   
Resolving deltas:  73% (372942/509791)   
Resolving deltas:  73% (376153/509791)   
Resolving deltas:  74% (377975/509791)   
Resolving deltas:  75% (382769/509791)   
Resolving deltas:  75% (384874/509791)   
Resolving deltas:  76% (387468/509791)   
Resolving deltas:  76% (391446/509791)   
Resolving deltas:  77% (392540/509791)   
[0:01:10] Still working on:
[0:01:10]   v8
Resolving deltas:  77% (396675/509791)   
Resolving deltas:  78% (397811/509791)   
Resolving deltas:  79% (402753/509791)   
Resolving deltas:  79% (402872/509791)   
Resolving deltas:  80% (411187/509791)   
Resolving deltas:  80% (411378/509791)   
Resolving deltas:  81% (412979/509791)   
[0:01:20] Still working on:
[0:01:20]   v8
Resolving deltas:  81% (415620/509791)   
Resolving deltas:  82% (418224/509791)   
Resolving deltas:  82% (419460/509791)   
Resolving deltas:  83% (423197/509791)   
Resolving deltas:  83% (425151/509791)   
Resolving deltas:  84% (429456/509791)   
Resolving deltas:  84% (431342/509791)   
Resolving deltas:  84% (432677/509791)   
Resolving deltas:  85% (433486/509791)   
Resolving deltas:  86% (438515/509791)   
Resolving deltas:  86% (439905/509791)   
Resolving deltas:  87% (443848/509791)   
Resolving deltas:  88% (448626/509791)   
Resolving deltas:  88% (449667/509791)   
[0:01:30] Still working on:
[0:01:30]   v8
Resolving deltas:  88% (451061/509791)   
Resolving deltas:  88% (452943/509791)   
Resolving deltas:  89% (453732/509791)   
Resolving deltas:  89% (456363/509791)   
Resolving deltas:  90% (459041/509791)   
Resolving deltas:  90% (462532/509791)   
Resolving deltas:  91% (464131/509791)   
Resolving deltas:  91% (465694/509791)   
Resolving deltas:  92% (469055/509791)   
Resolving deltas:  92% (469724/509791)   
Resolving deltas:  92% (473802/509791)   
Resolving deltas:  93% (474137/509791)   
Resolving deltas:  94% (479432/509791)   
Resolving deltas:  94% (480493/509791)   
Resolving deltas:  94% (481956/509791)   
[0:01:40] Still working on:
[0:01:40]   v8
Resolving deltas:  95% (484782/509791)   
Resolving deltas:  96% (489417/509791)   
Resolving deltas:  97% (494716/509791)   
Resolving deltas:  97% (499406/509791)   
Resolving deltas:  98% (500111/509791)   
Resolving deltas:  98% (503198/509791)   
Resolving deltas:  99% (504962/509791)   
Resolving deltas:  99% (506522/509791)   
Resolving deltas:  99% (509215/509791)   
Resolving deltas: 100% (509791/509791)   
Resolving deltas: 100% (509791/509791), done.
Checking connectivity... [0:01:50] Still working on:
[0:01:50]   v8
done.
[0:02:00] Still working on:
[0:02:00]   v8
[0:02:09] Still working on:
[0:02:09]   v8
________ running '/usr/bin/python v8/third_party/depot_tools/update_depot_tools_toggle.py --disable' in '/home/snake/projects/taxibus2/shared/bundle/ruby/2.5.0/gems/libv8-6.7.288.46.1/vendor'
________ running '/usr/bin/python v8/build/landmines.py --landmine-scripts v8/tools/get_landmines.py' in '/home/snake/projects/taxibus2/shared/bundle/ruby/2.5.0/gems/libv8-6.7.288.46.1/vendor'
________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-clang-format -s v8/buildtools/linux64/clang-format.sha1' in '/home/snake/projects/taxibus2/shared/bundle/ruby/2.5.0/gems/libv8-6.7.288.46.1/vendor'
0> Downloading v8/buildtools/linux64/clang-format...
Downloading 1 files took 13.680810 second(s)
Hook 'download_from_google_storage --no_resume '--platform=linux*' --no_auth --bucket chromium-clang-format -s v8/buildtools/linux64/clang-format.sha1' took 13.74 secs
________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-gn -s v8/buildtools/linux64/gn.sha1' in '/home/snake/projects/taxibus2/shared/bundle/ruby/2.5.0/gems/libv8-6.7.288.46.1/vendor'
0> Downloading v8/buildtools/linux64/gn...
Downloading 1 files took 3.876341 second(s)
________ running 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-spec-tests -s v8/test/wasm-spec-tests/tests.tar.gz.sha1' in '/home/snake/projects/taxibus2/shared/bundle/ruby/2.5.0/gems/libv8-6.7.288.46.1/vendor'
0> Downloading v8/test/wasm-spec-tests/tests.tar.gz...
0> Extracting 72 entries from v8/test/wasm-spec-tests/tests.tar.gz to v8/test/wasm-spec-tests/tests
Downloading 1 files took 3.576673 second(s)
________ running 'download_from_google_storage --no_resume --no_auth -u --bucket chromium-v8-closure-compiler -s v8/src/inspector/build/closure-compiler.tar.gz.sha1' in '/home/snake/projects/taxibus2/shared/bundle/ruby/2.5.0/gems/libv8-6.7.288.46.1/vendor'
0> Downloading v8/src/inspector/build/closure-compiler.tar.gz...
0> Extracting 4 entries from v8/src/inspector/build/closure-compiler.tar.gz to v8/src/inspector/build/closure-compiler
Downloading 1 files took 3.659086 second(s)
________ running '/usr/bin/python v8/build/linux/sysroot_scripts/install-sysroot.py --arch=x86' in '/home/snake/projects/taxibus2/shared/bundle/ruby/2.5.0/gems/libv8-6.7.288.46.1/vendor'
Installing Debian sid i386 root image: /home/snake/projects/taxibus2/shared/bundle/ruby/2.5.0/gems/libv8-6.7.288.46.1/vendor/v8/build/linux/debian_sid_i386-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/9e6279438ece6fb42b5333ca90d5e9d0c188a403/debian_sid_i386_sysroot.tar.xz
________ running '/usr/bin/python v8/third_party/binutils/download.py' in '/home/snake/projects/taxibus2/shared/bundle/ruby/2.5.0/gems/libv8-6.7.288.46.1/vendor'
0> Downloading /home/snake/projects/taxibus2/shared/bundle/ruby/2.5.0/gems/libv8-6.7.288.46.1/vendor/v8/third_party/binutils/Linux_ia32/binutils.tar.bz2...
Downloading 1 files took 3.603731 second(s)
0> Downloading /home/snake/projects/taxibus2/shared/bundle/ruby/2.5.0/gems/libv8-6.7.288.46.1/vendor/v8/third_party/binutils/Linux_x64/binutils.tar.bz2...
Downloading 1 files took 3.640955 second(s)
Downloading /home/snake/projects/taxibus2/shared/bundle/ruby/2.5.0/gems/libv8-6.7.288.46.1/vendor/v8/third_party/binutils/Linux_ia32/binutils.tar.bz2
Extracting /home/snake/projects/taxibus2/shared/bundle/ruby/2.5.0/gems/libv8-6.7.288.46.1/vendor/v8/third_party/binutils/Linux_ia32/binutils.tar.bz2
Downloading /home/snake/projects/taxibus2/shared/bundle/ruby/2.5.0/gems/libv8-6.7.288.46.1/vendor/v8/third_party/binutils/Linux_x64/binutils.tar.bz2
Extracting /home/snake/projects/taxibus2/shared/bundle/ruby/2.5.0/gems/libv8-6.7.288.46.1/vendor/v8/third_party/binutils/Linux_x64/binutils.tar.bz2
Hook '/usr/bin/python v8/third_party/binutils/download.py' took 10.59 secs
________ running '/usr/bin/python v8/tools/clang/scripts/update.py' in '/home/snake/projects/taxibus2/shared/bundle/ruby/2.5.0/gems/libv8-6.7.288.46.1/vendor'
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Linux_x64/clang-344066-1.tgz .......... Done.
________ running '/usr/bin/python v8/build/util/lastchange.py -o v8/build/util/LASTCHANGE' in '/home/snake/projects/taxibus2/shared/bundle/ruby/2.5.0/gems/libv8-6.7.288.46.1/vendor'
Running: gclient root
Running: gclient config --spec 'solutions = [
  {
    "url": "https://chromium.googlesource.com/v8/v8.git",
    "managed": False,
    "name": "v8",
    "deps_file": "DEPS",
    "custom_deps": {},
  },
]
'
Running: gclient sync --with_branch_heads
Running: git submodule foreach 'git config -f $toplevel/.git/config submodule.$name.ignore all'
Running: git config --add remote.origin.fetch '+refs/tags/*:refs/tags/*'
Running: git config diff.ignoreSubmodules all
Previous HEAD position was dc70449... undef min,max macros on windows
HEAD is now at a64db1f... Version 6.7.288.46
________ running '/usr/bin/python v8/build/landmines.py --landmine-scripts v8/tools/get_landmines.py' in '/home/snake/projects/taxibus2/shared/bundle/ruby/2.5.0/gems/libv8-6.7.288.46.1/vendor'
________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-clang-format -s v8/buildtools/linux64/clang-format.sha1' in '/home/snake/projects/taxibus2/shared/bundle/ruby/2.5.0/gems/libv8-6.7.288.46.1/vendor'
________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-luci -d v8/tools/luci-go/linux64' in '/home/snake/projects/taxibus2/shared/bundle/ruby/2.5.0/gems/libv8-6.7.288.46.1/vendor'
0> Downloading v8/tools/luci-go/linux64/isolate...
Downloading 1 files took 4.101099 second(s)
________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-gn -s v8/buildtools/linux64/gn.sha1' in '/home/snake/projects/taxibus2/shared/bundle/ruby/2.5.0/gems/libv8-6.7.288.46.1/vendor'
0> Downloading v8/buildtools/linux64/gn...
Downloading 1 files took 3.375053 second(s)
________ running 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-spec-tests -s v8/test/wasm-spec-tests/tests.tar.gz.sha1' in '/home/snake/projects/taxibus2/shared/bundle/ruby/2.5.0/gems/libv8-6.7.288.46.1/vendor'
0> Downloading v8/test/wasm-spec-tests/tests.tar.gz...
0> Removed v8/test/wasm-spec-tests/tests...
0> Extracting 72 entries from v8/test/wasm-spec-tests/tests.tar.gz to v8/test/wasm-spec-tests/tests
Downloading 1 files took 3.567359 second(s)
________ running 'download_from_google_storage --no_resume --no_auth -u --bucket chromium-v8-closure-compiler -s v8/src/inspector/build/closure-compiler.tar.gz.sha1' in '/home/snake/projects/taxibus2/shared/bundle/ruby/2.5.0/gems/libv8-6.7.288.46.1/vendor'
________ running '/usr/bin/python v8/build/linux/sysroot_scripts/install-sysroot.py --arch=x86' in '/home/snake/projects/taxibus2/shared/bundle/ruby/2.5.0/gems/libv8-6.7.288.46.1/vendor'
Installing Debian sid i386 root image: /home/snake/projects/taxibus2/shared/bundle/ruby/2.5.0/gems/libv8-6.7.288.46.1/vendor/v8/build/linux/debian_sid_i386-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/15b7efb900d75f7316c6e713e80f87b9904791b1/debian_sid_i386_sysroot.tar.xz
________ running '/usr/bin/python v8/third_party/binutils/download.py' in '/home/snake/projects/taxibus2/shared/bundle/ruby/2.5.0/gems/libv8-6.7.288.46.1/vendor'
0> Downloading /home/snake/projects/taxibus2/shared/bundle/ruby/2.5.0/gems/libv8-6.7.288.46.1/vendor/v8/third_party/binutils/Linux_ia32/binutils.tar.bz2...
Downloading 1 files took 3.723548 second(s)
0> Downloading /home/snake/projects/taxibus2/shared/bundle/ruby/2.5.0/gems/libv8-6.7.288.46.1/vendor/v8/third_party/binutils/Linux_x64/binutils.tar.bz2...
Downloading 1 files took 3.683810 second(s)
Downloading /home/snake/projects/taxibus2/shared/bundle/ruby/2.5.0/gems/libv8-6.7.288.46.1/vendor/v8/third_party/binutils/Linux_ia32/binutils.tar.bz2
Extracting /home/snake/projects/taxibus2/shared/bundle/ruby/2.5.0/gems/libv8-6.7.288.46.1/vendor/v8/third_party/binutils/Linux_ia32/binutils.tar.bz2
Downloading /home/snake/projects/taxibus2/shared/bundle/ruby/2.5.0/gems/libv8-6.7.288.46.1/vendor/v8/third_party/binutils/Linux_x64/binutils.tar.bz2
Extracting /home/snake/projects/taxibus2/shared/bundle/ruby/2.5.0/gems/libv8-6.7.288.46.1/vendor/v8/third_party/binutils/Linux_x64/binutils.tar.bz2
________ running '/usr/bin/python v8/tools/clang/scripts/update.py' in '/home/snake/projects/taxibus2/shared/bundle/ruby/2.5.0/gems/libv8-6.7.288.46.1/vendor'
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Linux_x64/clang-328716-2.tgz .......... Done.

WARNING: 'v8/third_party/depot_tools' is no longer part of this client.  It is recommended that you manually remove it.


WARNING: 'v8/test/wasm-js/data' is no longer part of this client.  It is recommended that you manually remove it.

Beginning compilation. This will take some time.
ERROR at //snapshot_toolchain.gni:101:1: Assertion failed.
assert(v8_snapshot_toolchain != "",
^-----
Do not know how to build a snapshot for //build/toolchain/linux:clang_ia32 on linux x86
See //BUILD.gn:19:1: whence it was imported.
import("snapshot_toolchain.gni")
^------------------------------
ninja: Entering directory `out.gn/libv8'
ninja: error: loading 'build.ninja': No such file or directory
/home/snake/projects/taxibus2/shared/bundle/ruby/2.5.0/gems/libv8-6.7.288.46.1/ext/libv8/location.rb:41:in `block in verify_installation!': libv8 did not install properly, expected binary v8 archive '/home/snake/projects/taxibus2/shared/bundle/ruby/2.5.0/gems/libv8-6.7.288.46.1/vendor/v8/out.gn/libv8/obj/libv8_monolith.a'to exist, but it was not found (Libv8::Location::Vendor::ArchiveNotFound)
	from /home/snake/projects/taxibus2/shared/bundle/ruby/2.5.0/gems/libv8-6.7.288.46.1/ext/libv8/location.rb:40:in `each'
	from /home/snake/projects/taxibus2/shared/bundle/ruby/2.5.0/gems/libv8-6.7.288.46.1/ext/libv8/location.rb:40:in `verify_installation!'
	from /home/snake/projects/taxibus2/shared/bundle/ruby/2.5.0/gems/libv8-6.7.288.46.1/ext/libv8/location.rb:26:in `install!'
	from extconf.rb:7:in `<main>'

extconf failed, exit code 1

```

**Comment by ignisf** [comment]
Hello,

That's an issue with libv8, I'll close this in favour of https://github.com/cowboyd/libv8/issues/272
