### ISSUE TITLE
ReferenceError: setTimeout is not defined

### ISSUE THREAD

**Issue by hex0wn** [discourse/mini_racer#135]
Here is my code
```
require 'mini_racer'
ctx = MiniRacer::Context.new
ctx.eval('setTimeout(function(){console.log(1)}, 1000)')
```
The error info is
```
Traceback (most recent call last):
	7: from 1.rb:3:in `<main>'
	6: from /usr/local/rvm/gems/ruby-2.5.3/gems/mini_racer-0.2.4/lib/mini_racer.rb:176:in `eval'
	5: from /usr/local/rvm/gems/ruby-2.5.3/gems/mini_racer-0.2.4/lib/mini_racer.rb:176:in `synchronize'
	4: from /usr/local/rvm/gems/ruby-2.5.3/gems/mini_racer-0.2.4/lib/mini_racer.rb:178:in `block in eval'
	3: from /usr/local/rvm/gems/ruby-2.5.3/gems/mini_racer-0.2.4/lib/mini_racer.rb:264:in `timeout'
	2: from /usr/local/rvm/gems/ruby-2.5.3/gems/mini_racer-0.2.4/lib/mini_racer.rb:179:in `block (2 levels) in eval'
	1: from /usr/local/rvm/gems/ruby-2.5.3/gems/mini_racer-0.2.4/lib/mini_racer.rb:179:in `eval_unsafe'
JavaScript at <anonymous>:1:1: ReferenceError: setTimeout is not defined (MiniRacer::RuntimeError)
```

I tried in `CentOS Linux release 7.5.1804` and `Ubuntu 16.04.5 LTS`

**Comment by SamSaffron** [comment]
setTimeout and setInterval are not defined by v8, the platform needs to
provide them. if you want timeout you are going to have to implement in
Ruby and attach the method.

**Comment by ianks** [comment]
I was thinking it might be useful to attach an (optional) event loop to a mini_racer context. Some libs require and event loop, so for now I just polyfill it like:

```js
// Pseudo since I'm on phone
function setTimeout(func) { func() }
```

Obvious correctness issues there, but "It Works" ™️.

There will be some complexity ensuring event loop is properly shut down and before exit, but it night be a worthwhile edition.

**Comment by SamSaffron** [comment]
Technically this is doable today I have a reasonably efficient implementation of timer thread at:

https://github.com/SamSaffron/message_bus/blob/master/lib/message_bus/timer_thread.rb

It would be pretty straight forward to glue it on by attaching stuff. It is a bit tricky though getting full details of the func being called out of the boundary, so you would may need some sort of weakmap or something.
