### ISSUE TITLE
Fail to install gem 'mini_racer'

### ISSUE THREAD

**Issue by Sega100500** [discourse/mini_racer#72]
In my Gemfile:
gem 'mini_racer'

```bundle install```

```
Fetching libv8 5.9.211.38.1
Installing libv8 5.9.211.38.1 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/libv8-5.9.211.38.1/ext/libv8
/home/ruby/.rbenv/versions/2.5.0/bin/ruby -r ./siteconf20171227-18139-z6o7p5.rb extconf.rb
creating Makefile

v8 (ERROR)
----------------------------------------
[0:00:00] Started.
[0:00:00]

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/v8/v8.git
/home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/libv8-5.9.211.38.1/vendor/_gclient_v8_vqSwQh' in
'/home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/libv8-5.9.211.38.1/vendor'
[0:00:00] Cloning into '/home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/libv8-5.9.211.38.1/vendor/_gclient_v8_vqSwQh'...
[0:00:02] remote: Sending approximately 533.65 MiB ...
[0:00:43] remote: Counting objects: 1
[0:00:44] remote: Counting objects: 1115
[0:00:45] remote: Counting objects: 7665, done
[0:00:45] remote: Finding sources:  20% (1/5)
[0:00:45] remote: Finding sources: 100% (5/5)
[0:00:45] Receiving objects:   0% (1/518315)
[0:00:46] Receiving objects:   6% (31099/518315), 10.38 MiB | 10.35 MiB/s
[0:00:47] Receiving objects:  10% (51832/518315), 15.99 MiB | 10.64 MiB/s
[0:00:48] Receiving objects:  13% (72171/518315), 27.16 MiB | 10.86 MiB/s
[0:00:49] Receiving objects:  19% (98480/518315), 43.99 MiB | 10.97 MiB/s
[0:00:50] Receiving objects:  25% (129579/518315), 55.24 MiB | 11.38 MiB/s
[0:00:51] Receiving objects:  31% (160678/518315), 66.48 MiB | 11.18 MiB/s
[0:00:52] Receiving objects:  36% (186594/518315), 77.73 MiB | 11.18 MiB/s
[0:00:54] Receiving objects:  53% (279768/518315), 94.56 MiB | 11.18 MiB/s
[0:00:55] Receiving objects:  54% (283568/518315), 105.77 MiB | 11.18 MiB/s
[0:00:57] Receiving objects:  56% (295017/518315), 127.53 MiB | 10.60 MiB/s
[0:00:59] Receiving objects:  57% (299185/518315), 149.96 MiB | 10.60 MiB/s
[0:01:00] Receiving objects:  58% (302347/518315), 161.14 MiB | 11.18 MiB/s
[0:01:01] Receiving objects:  58% (303692/518315), 172.39 MiB | 11.18 MiB/s
[0:01:02] Receiving objects:  58% (305578/518315), 183.63 MiB | 11.18 MiB/s
[0:01:03] Receiving objects:  59% (309233/518315), 194.85 MiB | 11.18 MiB/s
[0:01:04] Receiving objects:  59% (310845/518315), 206.06 MiB | 11.18 MiB/s
[0:01:06] Receiving objects:  61% (316173/518315), 222.81 MiB | 10.67 MiB/s
[0:01:07] Receiving objects:  61% (321205/518315), 233.65 MiB | 10.60 MiB/s
[0:01:08] Receiving objects:  62% (324120/518315), 244.86 MiB | 10.60 MiB/s
[0:01:10] Receiving objects:  64% (331722/518315), 267.36 MiB | 10.61 MiB/s
[0:01:11] Receiving objects:  65% (338957/518315), 278.59 MiB | 11.20 MiB/s
[0:01:12] Receiving objects:  65% (341590/518315), 289.72 MiB | 11.18 MiB/s
[0:01:13] Receiving objects:  66% (344386/518315), 300.91 MiB | 11.17 MiB/s
[0:01:14] Receiving objects:  67% (349175/518315), 312.15 MiB | 11.18 MiB/s
[0:01:15] Receiving objects:  69% (357638/518315), 328.96 MiB | 11.17 MiB/s
[0:01:17] Receiving objects:  70% (367143/518315), 343.08 MiB | 10.57 MiB/s
[0:01:18] Receiving objects:  72% (373187/518315), 360.26 MiB | 10.58 MiB/s
[0:01:20] Receiving objects:  73% (380342/518315), 376.93 MiB | 10.54 MiB/s
[0:01:21] Receiving objects:  75% (388737/518315), 393.32 MiB | 11.05 MiB/s
[0:01:23] Receiving objects:  77% (399103/518315), 410.18 MiB | 11.05 MiB/s
[0:01:24] Receiving objects:  77% (403442/518315), 421.37 MiB | 11.07 MiB/s
[0:01:25] Receiving objects:  78% (408013/518315), 432.62 MiB | 11.16 MiB/s
[0:01:26] Receiving objects:  79% (412574/518315), 443.86 MiB | 11.20 MiB/s
[0:01:27] Receiving objects:  81% (419836/518315), 457.86 MiB | 10.57 MiB/s
[0:01:29] Receiving objects:  82% (429265/518315), 474.73 MiB | 10.57 MiB/s
[0:01:30] Receiving objects:  85% (441656/518315), 485.91 MiB | 10.57 MiB/s
[0:01:31] Receiving objects:  89% (461301/518315), 497.16 MiB | 11.17 MiB/s
[0:01:32] Receiving objects:  93% (482033/518315), 514.02 MiB | 11.19 MiB/s
[0:01:33] Receiving objects:  97% (502766/518315), 525.21 MiB | 11.18 MiB/s
[0:01:34] remote: Total 518315 (delta 423617), reused 518311 (delta 423617)
[0:01:34] Receiving objects: 100% (518315/518315), 530.83 MiB | 11.18 MiB/s
[0:01:34] Resolving deltas:   0% (0/423617)
[0:01:35] Resolving deltas:  10% (42373/423617)
[0:01:36] Resolving deltas:  25% (105919/423617)
[0:01:37] Resolving deltas:  39% (166842/423617)
[0:01:38] Resolving deltas:  52% (222216/423617)
[0:01:39] Resolving deltas:  56% (237344/423617)
[0:01:40] Resolving deltas:  63% (266879/423617)
[0:01:41] Resolving deltas:  65% (275368/423617)
[0:01:42] Resolving deltas:  67% (283828/423617)
[0:01:44] Resolving deltas:  69% (292440/423617)
[0:01:45] Resolving deltas:  72% (305069/423617)
[0:01:46] Resolving deltas:  75% (317718/423617)
[0:01:47] Resolving deltas:  77% (329721/423617)
[0:01:48] Resolving deltas:  79% (337099/423617)
[0:01:49] Resolving deltas:  82% (348371/423617)
[0:01:50] Resolving deltas:  85% (360075/423617)
[0:01:51] Resolving deltas:  88% (372785/423617)
[0:01:53] Resolving deltas:  91% (385931/423617)
[0:01:54] Resolving deltas:  93% (393980/423617)
[0:01:55] Resolving deltas:  96% (406910/423617)
[0:01:56] Resolving deltas:  99% (421514/423617)
[0:01:57] Resolving deltas: 100% (423617/423617)
[0:01:57] Checking connectivity... done.
[0:02:27] From https://chromium.googlesource.com/v8/v8
[0:02:27]  * [new ref]         refs/branch-heads/0.1 -> branch-heads/0.1
[0:02:27]  * [new ref]         refs/branch-heads/0.3 -> branch-heads/0.3
[0:02:27]  * [new ref]         refs/branch-heads/1.1 -> branch-heads/1.1
[0:02:27]  * [new ref]         refs/branch-heads/1.2 -> branch-heads/1.2
[0:02:27]  * [new ref]         refs/branch-heads/1.3 -> branch-heads/1.3
[0:02:27]  * [new ref]         refs/branch-heads/2.0 -> branch-heads/2.0
[0:02:27]  * [new ref]         refs/branch-heads/2.1 -> branch-heads/2.1
[0:02:27]  * [new ref]         refs/branch-heads/2.2 -> branch-heads/2.2
[0:02:27]  * [new ref]         refs/branch-heads/2.3 -> branch-heads/2.3
[0:02:27]  * [new ref]         refs/branch-heads/2.4 -> branch-heads/2.4
[0:02:27]  * [new ref]         refs/branch-heads/2.5 -> branch-heads/2.5
[0:02:27]  * [new ref]         refs/branch-heads/3.0 -> branch-heads/3.0
[0:02:27]  * [new ref]         refs/branch-heads/3.1 -> branch-heads/3.1
[0:02:27]  * [new ref]         refs/branch-heads/3.10 -> branch-heads/3.10
[0:02:27]  * [new ref]         refs/branch-heads/3.11 -> branch-heads/3.11
[0:02:27]  * [new ref]         refs/branch-heads/3.12 -> branch-heads/3.12
[0:02:27]  * [new ref]         refs/branch-heads/3.13 -> branch-heads/3.13
[0:02:27]  * [new ref]         refs/branch-heads/3.14 -> branch-heads/3.14
[0:02:27]  * [new ref]         refs/branch-heads/3.15 -> branch-heads/3.15
[0:02:27]  * [new ref]         refs/branch-heads/3.16 -> branch-heads/3.16
[0:02:27]  * [new ref]         refs/branch-heads/3.17 -> branch-heads/3.17
[0:02:27]  * [new ref]         refs/branch-heads/3.18 -> branch-heads/3.18
[0:02:27]  * [new ref]         refs/branch-heads/3.19 -> branch-heads/3.19
[0:02:27]  * [new ref]         refs/branch-heads/3.2 -> branch-heads/3.2
[0:02:27]  * [new ref]         refs/branch-heads/3.20 -> branch-heads/3.20
[0:02:27]  * [new ref]         refs/branch-heads/3.20.15.5 -> branch-heads/3.20.15.5
[0:02:27]  * [new ref]         refs/branch-heads/3.21 -> branch-heads/3.21
[0:02:27]  * [new ref]         refs/branch-heads/3.22 -> branch-heads/3.22
[0:02:27]  * [new ref]         refs/branch-heads/3.23 -> branch-heads/3.23
[0:02:27]  * [new ref]         refs/branch-heads/3.24 -> branch-heads/3.24
[0:02:27]  * [new ref]         refs/branch-heads/3.25 -> branch-heads/3.25
[0:02:27]  * [new ref]         refs/branch-heads/3.26 -> branch-heads/3.26
[0:02:28]  * [new ref]         refs/branch-heads/3.27 -> branch-heads/3.27
[0:02:28]  * [new ref]         refs/branch-heads/3.28 -> branch-heads/3.28
[0:02:28]  * [new ref]         refs/branch-heads/3.29 -> branch-heads/3.29
[0:02:28]  * [new ref]         refs/branch-heads/3.3 -> branch-heads/3.3
[0:02:28]  * [new ref]         refs/branch-heads/3.30 -> branch-heads/3.30
[0:02:28]  * [new ref]         refs/branch-heads/3.31 -> branch-heads/3.31
[0:02:28]  * [new ref]         refs/branch-heads/3.4 -> branch-heads/3.4
[0:02:28]  * [new ref]         refs/branch-heads/3.5 -> branch-heads/3.5
[0:02:28]  * [new ref]         refs/branch-heads/3.6 -> branch-heads/3.6
[0:02:28]  * [new ref]         refs/branch-heads/3.7 -> branch-heads/3.7
[0:02:28]  * [new ref]         refs/branch-heads/3.8 -> branch-heads/3.8
[0:02:28]  * [new ref]         refs/branch-heads/3.9 -> branch-heads/3.9
[0:02:28]  * [new ref]         refs/branch-heads/4.1 -> branch-heads/4.1
[0:02:28]  * [new ref]         refs/branch-heads/4.2 -> branch-heads/4.2
[0:02:28]  * [new ref]         refs/branch-heads/4.2.39 -> branch-heads/4.2.39
[0:02:28]  * [new ref]         refs/branch-heads/4.3 -> branch-heads/4.3
[0:02:28]  * [new ref]         refs/branch-heads/4.4 -> branch-heads/4.4
[0:02:28]  * [new ref]         refs/branch-heads/4.5 -> branch-heads/4.5
[0:02:28]  * [new ref]         refs/branch-heads/4.6 -> branch-heads/4.6
[0:02:28]  * [new ref]         refs/branch-heads/4.7 -> branch-heads/4.7
[0:02:28]  * [new ref]         refs/branch-heads/4.8 -> branch-heads/4.8
[0:02:28]  * [new ref]         refs/branch-heads/4.9 -> branch-heads/4.9
[0:02:28]  * [new ref]         refs/branch-heads/5.0 -> branch-heads/5.0
[0:02:28]  * [new ref]         refs/branch-heads/5.1 -> branch-heads/5.1
[0:02:28]  * [new ref]         refs/branch-heads/5.2 -> branch-heads/5.2
[0:02:28]  * [new ref]         refs/branch-heads/5.3 -> branch-heads/5.3
[0:02:28]  * [new ref]         refs/branch-heads/5.4 -> branch-heads/5.4
[0:02:28]  * [new ref]         refs/branch-heads/5.5 -> branch-heads/5.5
[0:02:28]  * [new ref]         refs/branch-heads/5.6 -> branch-heads/5.6
[0:02:28]  * [new ref]         refs/branch-heads/5.7 -> branch-heads/5.7
[0:02:28]  * [new ref]         refs/branch-heads/5.8 -> branch-heads/5.8
[0:02:28]  * [new ref]         refs/branch-heads/5.9 -> branch-heads/5.9
[0:02:28]  * [new ref]         refs/branch-heads/6.0 -> branch-heads/6.0
[0:02:28]  * [new ref]         refs/branch-heads/6.1 -> branch-heads/6.1
[0:02:28]  * [new ref]         refs/branch-heads/6.2 -> branch-heads/6.2
[0:02:28]  * [new ref]         refs/branch-heads/6.3 -> branch-heads/6.3
[0:02:28]  * [new ref]         refs/branch-heads/6.4 -> branch-heads/6.4
[0:02:28]  * [new ref]         refs/branch-heads/experimental -> branch-heads/experimental
[0:02:28]  * [new ref]         refs/branch-heads/test-gnumbd -> branch-heads/test-gnumbd
[0:02:28] Checked out refs/remotes/origin/master to a detached HEAD. Before making any commits
in this repo, you should use 'git checkout <branch>' to switch to
an existing branch or use 'git checkout origin -b <branch>' to
create a new branch for your work.
[0:02:28]
----------------------------------------
Traceback (most recent call last):
  File "/home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/libv8-5.9.211.38.1/vendor/depot_tools/gclient.py", line 2523, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/libv8-5.9.211.38.1/vendor/depot_tools/gclient.py", line 2509, in main
    return dispatcher.execute(OptionParser(), argv)
  File "/home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/libv8-5.9.211.38.1/vendor/depot_tools/subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "/home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/libv8-5.9.211.38.1/vendor/depot_tools/gclient.py", line 2270, in CMDsync
    ret = client.RunOnDeps('update', args)
  File "/home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/libv8-5.9.211.38.1/vendor/depot_tools/gclient.py", line 1464, in RunOnDeps
    work_queue.flush(revision_overrides, command, args, options=self._options)
  File "/home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/libv8-5.9.211.38.1/vendor/depot_tools/gclient_utils.py", line 1050, in run
    self.item.run(*self.args, **self.kwargs)
  File "/home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/libv8-5.9.211.38.1/vendor/depot_tools/gclient.py", line 902, in run
    self.ParseDepsFile()
File "/home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/libv8-5.9.211.38.1/vendor/depot_tools/gclient.py", line 700, in
ParseDepsFile
    gclient_eval.Exec(deps_content, global_scope, local_scope, filepath)
  File "/home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/libv8-5.9.211.38.1/vendor/depot_tools/gclient_eval.py", line 218, in Exec
    _GCLIENT_SCHEMA.validate(local_scope)
File "/home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/libv8-5.9.211.38.1/vendor/depot_tools/third_party/schema/schema.py", line
254, in validate
    raise SchemaError([k] + x.autos, [e] + x.errors)
third_party.schema.schema.SchemaError: Key 'vars' error:
Key 'checkout_instrumented_libraries' error:
False should be instance of 'basestring'
Running: gclient root
Running: gclient config --spec 'solutions = [
  {
    "url": "https://chromium.googlesource.com/v8/v8.git",
    "managed": False,
    "name": "v8",
    "deps_file": "DEPS",
    "custom_deps": {},
  },
]
'
Running: gclient sync --with_branch_heads
Traceback (most recent call last):
  File "/home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/libv8-5.9.211.38.1/vendor/depot_tools/fetch.py", line 299, in <module>
    sys.exit(main())
  File "/home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/libv8-5.9.211.38.1/vendor/depot_tools/fetch.py", line 294, in main
    return run(options, spec, root)
  File "/home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/libv8-5.9.211.38.1/vendor/depot_tools/fetch.py", line 288, in run
    return checkout.init()
  File "/home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/libv8-5.9.211.38.1/vendor/depot_tools/fetch.py", line 131, in init
    self.run_gclient(*sync_cmd)
  File "/home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/libv8-5.9.211.38.1/vendor/depot_tools/fetch.py", line 78, in run_gclient
    return self.run(cmd_prefix + cmd, **kwargs)
  File "/home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/libv8-5.9.211.38.1/vendor/depot_tools/fetch.py", line 68, in run
    return subprocess.check_output(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '('gclient', 'sync', '--with_branch_heads')' returned non-zero exit status 1
/home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/libv8-5.9.211.38.1/ext/libv8/builder.rb:117:in `block in setup_build_deps!':
unable to fetch v8 source (RuntimeError)
        from /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/libv8-5.9.211.38.1/ext/libv8/builder.rb:115:in `chdir'
        from /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/libv8-5.9.211.38.1/ext/libv8/builder.rb:115:in `setup_build_deps!'
        from /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/libv8-5.9.211.38.1/ext/libv8/builder.rb:71:in `build_libv8!'
        from /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/libv8-5.9.211.38.1/ext/libv8/location.rb:24:in `install!'
        from extconf.rb:7:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/libv8-5.9.211.38.1 for inspection.
Results logged to /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/extensions/x86_64-linux/2.5.0-static/libv8-5.9.211.38.1/gem_make.out

An error occurred while installing libv8 (5.9.211.38.1), and Bundler cannot continue.
Make sure that `gem install libv8 -v '5.9.211.38.1'` succeeds before bundling.

In Gemfile:
  mini_racer was resolved to 0.1.14, which depends on
    libv8
```

I try ```gem install libv8 -v '5.9.211.38.1'``` - all Ok.
But error install gem exists.

Config:
Ruby 2.5.0
Server version: Apache/2.4.10 (Debian)
Linux Debian 8.10

**Comment by ignisf** [comment]
The install failure you're experiencing is unrelated to `mini_racer`.

**Comment by Sega100500** [comment]
@ignisf
And what is the failure of the installation, let me ask?

In ```Gemfile``` simple wrote ```gem 'mini_racer'```, then run ```bundle install```

Whats WRONG?!

**Comment by krzysiek1507** [comment]
Here is the answer:
`An error occurred while installing libv8 (5.9.211.38.1), and Bundler cannot continue.`

**Comment by Sega100500** [comment]
@krzysiek1507 
Very clever!
This is a parts of ONE system - Everything is interconnected - error in one = error in all !

**Comment by krzysiek1507** [comment]
`mini_racer` uses `libv8`. If `libv8` doesn't compile, you need to ask for help on it's Github.

**Comment by Sega100500** [comment]
@krzysiek1507 
Where I already only asked or reported. Everywhere one answer: "This is not ours! Everything is working fine for us!"
if ```mini_racer``` uses ```libv8```, then ```libv8``` MUST work too!!! To be able to believe that the system is fully operational.

**Comment by krzysiek1507** [comment]
Have you seen more people with the same issue? No? So you are the first and there is a case when libv8 doesn't compile. Please provide as much as possible data to the libv8 team and be patient. It's holiday time so probably you can expect an answer in January.

**Comment by Sega100500** [comment]
@krzysiek1507 
I gave more than complete information! Let them continue to celebrate, even though a year later they will recover. I already found a solution for myself.
About the problem, I reported, and then they have to decide how their product will be - working, or written with crooked hands.

**Comment by Sega100500** [comment]
@krzysiek1507 
The level of education and education of people is declining and falling everywhere. That's really really sad! So we get non-functioning systems.

**Comment by krzysiek1507** [comment]
You don't need to use any library available for ruby. You can write everything yourself if you think that you can do it better. Being rude doesn't help you.

**Comment by Sega100500** [comment]
@krzysiek1507 
I already write almost everything myself, because there is very little hope for others that everything will be done as it should, right. I also struggled with this problem only because the system itself as a whole ceased to be launched, to work correctly.
This is not rude, but sarcasm in a rigid form!

**Comment by BenTalagan** [comment]
@Sega100500 
The licenses of mini_racer/libv8/rails and other libraries are pretty clear : their spirit is that they are made in a best-effort, community generosity. It does not mean that people working on these projects are tied to a professional or business rigor in any way towards their users. Generally, they will provide a lot of effort and give a lot of their time for free - which to my humble opinion is, on the contrary, a sign of a good level of education. Although we could probably solidly defend some point of views about a decline in numerous ways human beings behave nowadays, it sounds really odd to me to choose the open-source community as a general illustration for this! :)

**Comment by Sega100500** [comment]
@BenTalagan
If you can and can do - do it, do it well! And then write off on the terms of the license, simply because the brains were not enough or just fed up - rather unethical in relation to users of these systems.
Either do it if you want and you can, but do it from the heart, well, or do not do it at all in life! Everything we do must be done well, conscientiously and without excuses for a license.
Or now a license - is there a way to justify that you can not do well what you are doing?

**Comment by BenTalagan** [comment]
Your logic sounds so odd : so, since mini_racer/libv8/rails are part of your projects, why not integrate them perfectly well with all your heart and passion and fix all currently open issues - is there a way to justify that you use unperfect and flawed libraries given freely by the community into your projects without fixing all the existing known problems that are part of them?

Secondly, I am not in the head of the people who wrote mini_racer, but judging by their discussions I'm more than convinced that they put quite a good amount of 'heart' in what they do. And brain. - you're not probably aware of this, but the level of knowledge and skillfulness is pretty pretty high on a project like mini_racer.

**Comment by SamSaffron** [comment]
> The level of education and education of people is declining and falling everywhere. That's really really sad!  

So your strategy here is to call people stupid until they fix your problem?

**Comment by Sega100500** [comment]
@SamSaffron 
Of course not! I specifically do not want to offend anyone, only this is a general, global trend.
Moreover, the issue is closed, therefore, no one was going to fix anything. With the words: "Everything is working for us, everything is fine" just closed the issue.

**Comment by Sega100500** [comment]
@BenTalagan 
Yes, I believe that the RoR is a system of many components, and that each component should work, work correctly. Otherwise, the whole system will collapse in the end.
If the user can not normally use the system "as is", if you constantly have to do some tricks, then in the end, such a user spits and says that this system is worthless, bad.
I believe that even if ```therubyracer``` is dead, it is in the interest of the community to somehow try to correct the situation, rather than brush it aside: "This is part of the system, but not our part, everything works well for us."

**Comment by Sega100500** [comment]
The issue was closed, no one thought that it was necessary to correct something. If this is not even directly related to this component, then you should try to correct the component that the non-functionality depends on.
**This speaks volumes about many things.**

**Comment by SamSaffron** [comment]
This was closed here cause the issue should be reported here:

https://github.com/cowboyd/libv8/issues

Same as you do not report issues with mini racer at:

https://www.kernel.org/pub/linux/docs/lkml/reporting-bugs.html

or here

https://bugs.ruby-lang.org/projects/ruby-trunk

Yes, we want the bug fixed but there is a protocol you follow in an open source ecosystem and that means you should be reporting bugs to the right place. 

>This speaks volumes about many things.

I am pretty offended that you are using my bug tracker here as your personal festivus.
