### ISSUE TITLE
Error parsing Javascript

### ISSUE THREAD

**Issue by AndrewRayCode** [discourse/mini_racer#78]
Since it's parsing a line that's several megabytes, I can't narrow down the specific area causing the problem. Here's the stack:

```
Caused by:
MiniRacer::RuntimeError: Error
JavaScript at new JS_Parse_Error (<anonymous>:3572:11870)
JavaScript at js_error (<anonymous>:3572:12089)
JavaScript at croak (<anonymous>:3572:20898)
JavaScript at token_error (<anonymous>:3572:21035)
JavaScript at unexpected (<anonymous>:3572:21123)
JavaScript at semicolon (<anonymous>:3572:21615)
JavaScript at simple_statement (<anonymous>:3572:24478)
JavaScript at <anonymous>:3572:22447
JavaScript at <anonymous>:3572:21788
JavaScript at block_ (<anonymous>:3572:26497)
```

**Comment by AndrewRayCode** [comment]
It's from trying to parse the source code of https://github.com/ericnorris/striptags/blob/master/src/striptags.js which is perfectly valid javascript

**Comment by SamSaffron** [comment]
I am not sure what to do here, this looks to me like a standard error that scriptjs is raising when its failing to parse whatever template you are passing it.

**Comment by AndrewRayCode** [comment]
Err, sorry, what is scriptjs? Are you saying the error is coming from a dependency used by mini_racer?

To clarify an assumption: my project _includes_ the above `striptags.js`, and when mini_racer tries to parse the source code (file linked above) of that, mini_racer raises an error. I'm not passing any runtime templates to striptags.

**Comment by aviat** [comment]
@AndrewRayCode are you having the same error if running this in Node?

**Comment by AndrewRayCode** [comment]
It's valid Javascript, there's no errors in regular JS environments

**Comment by SamSaffron** [comment]
I need a gist or repo reproducing the error to be able to look at it, it simply looks like your code is raising an exception.

**Comment by SamSaffron** [comment]
I am so sorry Andrew, but there is no way we can help out here without a standalone reproduction of the issue. 

MiniRacer is not a regular JS environment depending on how you define regular... for example you have no DOM like you do in the browser, you don't have all the libraries that node includes and so on.

**Comment by AndrewRayCode** [comment]
As shown in the bug report, this may be a parse error by mini_racer, where it's unable to parse valid javascript. I thought the test case was clear from linking to the file causing issues. The linked file leads to reproducible test cases. Following the example from this project's Readme, I was able to do to this:

```
require 'mini_racer'

context = MiniRacer::Context.new
puts context.eval "const NORMALIZE_TAG_REGEX = /<\/?([^\s\/>]+)/;"
puts 'done'
```
error:
```
ruby-2.1.1/gems/mini_racer-0.1.15/lib/mini_racer.rb:182:in `eval_unsafe': Uncaught SyntaxError: Unexpected token ^ at undefined:1:34 (MiniRacer::ParseError)
from ruby-2.1.1/gems/mini_racer-0.1.15/lib/mini_racer.rb:182:in `block (2 levels) in eval'
from ruby-2.1.1/gems/mini_racer-0.1.15/lib/mini_racer.rb:241:in `call'
from ruby-2.1.1/gems/mini_racer-0.1.15/lib/mini_racer.rb:241:in `timeout'
from ruby-2.1.1/gems/mini_racer-0.1.15/lib/mini_racer.rb:181:in `block in eval'
from ruby-2.1.1/gems/mini_racer-0.1.15/lib/mini_racer.rb:69:in `block in with_lock'
from ruby-2.1.1/gems/mini_racer-0.1.15/lib/mini_racer.rb:69:in `synchronize'
from ruby-2.1.1/gems/mini_racer-0.1.15/lib/mini_racer.rb:69:in `with_lock'
from ruby-2.1.1/gems/mini_racer-0.1.15/lib/mini_racer.rb:179:in `eval'
from c.rb:5:in `<main>'
```
This is perfectly valid Javascript:

<img width="338" alt="screen shot 2018-03-21 at 11 01 17 pm" src="https://user-images.githubusercontent.com/79215/37753769-d04380a8-2d5b-11e8-863a-6395bc1fa272.png">

Here's another example, from stripping down the file's code:

```
require 'mini_racer'

source_code = <<-EOF
const char = 'a';
switch (char) {
    case '\'':
        'do nothing'
}
EOF

context = MiniRacer::Context.new
puts context.eval source_code
puts 'done'
```
errors with:
```
mini_racer-0.1.15/lib/mini_racer.rb:182:in `eval_unsafe': Uncaught SyntaxError: Invalid or unexpected token at undefined:3:11 (MiniRacer::ParseError)
from mini_racer-0.1.15/lib/mini_racer.rb:182:in `block (2 levels) in eval'
from mini_racer-0.1.15/lib/mini_racer.rb:241:in `call'
from mini_racer-0.1.15/lib/mini_racer.rb:241:in `timeout'
from mini_racer-0.1.15/lib/mini_racer.rb:181:in `block in eval'
from mini_racer-0.1.15/lib/mini_racer.rb:69:in `block in with_lock'
from mini_racer-0.1.15/lib/mini_racer.rb:69:in `synchronize'
from mini_racer-0.1.15/lib/mini_racer.rb:69:in `with_lock'
from mini_racer-0.1.15/lib/mini_racer.rb:179:in `eval'
from c.rb:12:in `<main>'
```
and of course this is also perfectly valid javascript:
<img width="174" alt="screen shot 2018-03-21 at 11 03 17 pm" src="https://user-images.githubusercontent.com/79215/37753831-165582c6-2d5c-11e8-9d5e-7acf42d86513.png">

Am I missing some context? Wrong v8 version? Constructing my strings incorrectly? Wrong ruby version (2.1.1?)? These were all trivial to reproduce using the library from the bug report. It appears mini_racer is not able to parse several types of valid javascript, and this seems to be a **parse error, not a runtime error**(?)

**Comment by SamSaffron** [comment]
What you are describing there is a legit parse error though and incorrect JavaScript. 

```
[1] pry(main)> a = "'\''"
=> "'''"
```
You want this, which works:

```
source_code = <<-EOF
const char = 'a';
switch (char) {
    case '\\'':
        'do nothing'
}
EOF
```

**Comment by AndrewRayCode** [comment]
@SamSaffron The code you pasted is invalid. You escape a `\`, as in `\\`, meaning you have unbalanced quotes (three single quotes):
<img width="366" alt="screen shot 2018-03-22 at 9 03 00 am" src="https://user-images.githubusercontent.com/79215/37782328-df30a34e-2daf-11e8-9f65-0150f59bbbd0.png">

I believe both code blocks I've pasted are **valid javascript,** confirmed by pasting each block both in node (8.6.0 but version shouldn't matter) and a Chrome browser inspector:
```javascript
const NORMALIZE_TAG_REGEX = /<\/?([^\s\/>]+)/;
```
```javascript
const char = 'a';
switch (char) {
    case '\'':
        'do nothing'
}
```

However `mini_racer` is unable to parse these two blocks of valid Javascript.

**Comment by Supermathie** [comment]
@AndrewRayCode `const NORMALIZE_TAG_REGEX = /<\/?([^\s\/>]+)/;` is valid JS, but that's not what is being passed to the `context.eval` call as Ruby is consuming the backslashes. Consider the following difference:

```
irb(main):001:0> "const NORMALIZE_TAG_REGEX = /<\/?([^\s\/>]+)/;"
=> "const NORMALIZE_TAG_REGEX = /</?([^ />]+)/;"

irb(main):002:0> 'const NORMALIZE_TAG_REGEX = /<\/?([^\s\/>]+)/;'
=> "const NORMALIZE_TAG_REGEX = /<\\/?([^\\s\\/>]+)/;"
```

Your fixed example:

```
require 'mini_racer'

source_code = <<'EOF'
const char = 'a';
switch (char) {
    case '\'':
        'do nothing'
}
EOF

context = MiniRacer::Context.new
puts context.eval source_code
puts 'done'
```

**Comment by AndrewRayCode** [comment]
Ooooh got it, yes I was misinterpreting how multiline string escaping works in source ruby.

When rendering a react app with react_on_rails, the introduction of the mentioned `striptags` library caused a problem with our asset *build* system, the original error I posted. Removing the striptags library also removed the mini_racer error. Because it is part of several megabytes of javascript, it is not easy to debug. The app runs fine in the browser and in node with the same javascript source, it's only mini_racer that complains.

I will try to narrow down something more reproducible. Thanks for dealing with my misunderstanding. I do wonder why and what mini_racer is complaining about though.
